name: jaoProtector
main: com.jaoafa.jaoProtector.JaoProtector
version: 0.0.1
description: jao Minecraft Server 保護プラグイン
database: true
softdepend: [PermissionsEx, LuckPerms]
author: mine_book000
commands:
   jaoprotector:
      description: このプラグインに関する設定や情報が確認できます。
      usage: /<command>
      permission: jaosuperachievement.jaoprotector
      permission-message: You do not have permission to perform this command.